
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${APP_IMAGE}
    container_name: laravel-app
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      FILESYSTEM_DISK: ${FILESYSTEM_DISK}
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    depends_on:
      - db
    
  db:
      image: postgres:latest
      container_name: postgres_db
      restart: unless-stopped
      environment:
        DB_CONNECTION: ${DB_CONNECTION}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  nginx:
      image: nginx:stable-alpine3.21-perl
      container_name: nginx_server
      restart: unless-stopped
      ports:
        - "${NGINX_PORT}:80"
      volumes:
        - ./:/var/www
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - app

volumes:
  pgdata: